# Generated by Django 4.0.4 on 2022-05-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admininterface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destination',
            new_name='studentdata',
        ),
    ]
